### ISSUE TITLE
Every test question must contain Information text-area field

### ISSUE THREAD

**Issue by ichyr** [SoftServeUniversity/IF-044-UI#70]
Текст-placeholder: Пояснення до питання
1. test creation
2. test edit
3. test moderation

**Comment by ichyr** [comment]
Бачите, у темплейті відповідей є слово пояснення - то це саме те поле, якого ви ще не додали!

![image](https://cloud.githubusercontent.com/assets/4025556/3311486/f2f96cf6-f6c4-11e3-9752-4c3bd0536075.png)

**Comment by DimaKogut** [comment]
okey, check
