### ISSUE TITLE
score of test page

### ISSUE THREAD

**Issue by DimaKogut** [SoftServeUniversity/IF-044-UI#98]
![hhhhh](https://cloud.githubusercontent.com/assets/7049624/3464585/02127268-0251-11e4-8fc5-e0ad1e028c91.jpg)

Ivan, do i need to add link to categoty page of "sport"(1) and subcategoty page of "subcategory"(2) respectively?

and please, comment the design of page, is it exactly what you need?

**Comment by DimaKogut** [comment]
![jjjjjjjjjjjjjjj](https://cloud.githubusercontent.com/assets/7049624/3464618/e852e7a8-0251-11e4-839b-1741bdc5acf6.png)

**Comment by ichyr** [comment]
Yes.

Text must be black, when not focused.
